---

- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: update Debian/Ubuntu repositories
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: False
      become: yes

    - name: install packages
      become: yes
      package:
        name:
          - ansible
          - neofetch
        state: latest

  tasks:
    - name: create ansible user
      tags: always
      user:
        name: ansible
        groups: root
        state: present
        createhome: yes

    - name: add ssh key for ansible
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7ZKCfGHSEDKqwD7MuL/8y0G2rxSyFESJwkcm17vcT8 ansible"

    - name: add sudoers file for ansible
      tags: always
      become: yes
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: create user bean
      user:
        name: bean
        group: bean
        state: present
        createhome: yes

    - name: add sudoers file for bean
      tags: always
      become: yes
      copy:
        src: sudoer_bean
        dest: /etc/sudoers.d/bean
        owner: root
        group: root
        mode: 0440

    - name: Install SSH key for user 'bean'
      authorized_key:
        user: bean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIefOlgTs7w/n/wGGv4LWhOfVwzwmbsQx6VB6/cy/Jo acer_bean"
        state: present

    - name: Disable root login in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      become: yes
      notify: Restart SSH

    - name: Disable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/bean/.bashrc
        owner: bean
        group: bean
        mode: "0644"
      register: result

    - debug:
        var: result

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

- hosts: dns
  tasks:
    - name: users | bean | remove preinstalled clutter from home directory
      file:
        path: /home/bean/{{ item }}
        state: absent
      with_items:
        - examples.desktop
        - Desktop
        - Documents
        - Downloads
        - Music
        - Pictures
        - Public
        - Templates
        - Videos

    - name: users | bean | create personal directories
      tags: always
      become: yes
      file:
        path: /home/bean/{{ item.dir }}
        state: directory
        owner: bean
        group: bean
        mode: 0700
      with_items:
        - { dir: desktop }
        - { dir: documents }
        - { dir: downloads }
        - { dir: templates }
