---
- name: Basic Updates
  hosts: all
  become: true

  pre_tasks:
    - name: update repositories (Debian, Ubuntu)
      apt:
        update_cache: yes
      changed_when: False

  tasks:
  - name: install packages
    package:
      name:
        - fail2ban

  - name: install updates (Debian, Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "debian, Ubuntu"
