---
- name: Configure initial settings
  hosts: all
  become: yes  # Run tasks with sudo privileges

  pre_tasks:
    - name: update Debian/Ubuntu repositories
      apt:
        update_cache: yes
      changed_when: False
      become: yes

  tasks:
    - name: install packages
      package:
        name:
          - sudo
          - crowdsec
        state: latest
        update_cache: yes

    - name: add sudoers file for bean
      copy:
        src: sudoer_bean
        dest: /etc/sudoers.d/bean
        owner: root
        group: root
        mode: 0440

    - name: Install SSH key for user 'bean'
      authorized_key:
        user: bean
        key: "{{ lookup('file', 'files/acer_bean.pub') }}"
        state: present

    - name: Install public SSH key for user 'ansible'
      authorized_key:
        user: ansible
        key: "{{ lookup('file', 'files/ansible.pub') }}"
        state: present

    - name: add sudoers file for ansible
      copy: 
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: Disable root login in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      become: yes
      notify: Restart SSH

    - name: Disable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/bean/.bashrc
        owner: bean
        group: bean

---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: jay
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: jay
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/jay/.bashrc
     owner: jay
     group: jay

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/gratefulbean/ansible.git

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
