---
- name: System Update and User Setup
  hosts: all
  become: true

  vars:
    username: bean

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Perform system upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == 'Debian'

    - name: Install sudo, fail2ban
      apt:
        name: sudo, fail2ban
        state: present 

    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory

    - name: Create user bean
      user:
        name: "{{ username }}"
        password: $y$j9T$ez.LuqKP8wiFyyUxPw44A/$flCPclyw.cjCdd/LYeEHEa9OKjvR/flt.Ew.9IPWQbD
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Add sudoers file for user bean
      template:
        src: files/sudoers
        dest: /etc/sudoers.d/"{{ username }}"
        mode: 0440

    - name: Add SSH key for user bean
      authorized_key:
        user: "{{ username }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIefOlgTs7w/n/wGGv4LWhOfVwzwmbsQx6VB6/cy/Jo acer_bean"
        state: present

    - name: Copy files .bashrc, sshd_config
      copy:
        src: files/bashrc.backup
        dest: "/home/{{ username }}/.bashrc"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644
      copy:
        src: files/sshd_config.backup
        dest: "/etc/ssh/sshd_config"
        owner: "root"
        group: "root"
      notify: restart_sshd

-  hosts: all
   become: yes

   tasks:
     - name: Create user ansible
       user:
         name: "ansible"
         system: yes
         group: sudo

     - name: set up sudo for ansible user
       copy:
         src: files/sudoers
         dest: /etc/sudoers.d/ansible 
         owner: root
         group: root
         mode: 0440

     - name: Add SSH key for ansible
       authorized_key: 
         user: "ansible"
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7ZKCfGHSEDKqwD7MuL/8y0G2rxSyFESJwkcm17vcT8 ansible"
         state: present 
      # vars:
      #   username: ansible  
    
     #- name: add ansible-pull cron job
     # cron:
       # name: ansible auto-provision
       # user: velociraptor
       # minute: "*/10"
       # job: ansible-pull -o -U https://github.com/jlacroix82/ansible_pull_tutorial.git

